version: "3"

services:
  caddy:
    image: oaasgaa01/caddy-revproxy:latest
    container_name: "caddy-revproxy"
    restart: unless-stopped
    ports:
      - "2015:2015"
      - "80:80"
      - "443:443"
    volumes:
      - revproxy_data:/data
      - revproxy_config:/config
volumes:
  revproxy_data:
  revproxy_config:
