version: "3"

services:
  caddy:
    image: oaasgaa01/caddy-revproxy:latest
    container_name: "caddy-revproxy"
    restart: unless-stopped
    ports:
      - "2015:2015"
      - "2016:80"
      - "2017:443"
    # volumes:
    #   - caddy_config:/etc/caddy
#      - $PWD/site:/srv
#      - caddy_data:/data
#      - caddy_config:/config

# volumes:
#   caddy_config:
