version: "3"

services:
  proxy:
    # image: oaasgaa01/caddy-revproxy:latest
    image: caddy:2.2.1-alpine
    # container_name: "caddy-revproxy"
    restart: unless-stopped
    ports:
      - "2015:2015"
      - "80:80"
      - "443:443"
    volumes:
      - data:/data
      - config:/config
      - ./caddy:/etc/caddy
volumes:
  data:
  config:
  caddy:
